export const POST_CREATE_REQUEST='POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS='POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL='POST_CREATE_FAIL';

export const POST_FETCH_REQUEST='POST_FETCH_REQUEST';
export const POST_FETCH_SCUCCESS='POST_FETCH_SCUCCESS';
export const POST_FETCH_FAIL='POST_FETCH_FAIL';


export const SINGLE_POST_FETCH_REQUEST='SINGLE_POST_FETCH_REQUEST';
export const SINGLE_POST_FETCH_SUCCESS='SINGLE_POST_FETCH_SUCCESS';
export const SINGLE_POST_FETCH_FAIL='SINGLE_POST_FETCH_FAIL';

